# |---------- Environment parameters ----------|

board:
  size: 6
  shape: diamond #diamond or triangle

game:
  type: Peg #Hex
  open_positions: [[2,1],[0,0],[1,1]] # 4d: [2,1][1,2] 5t: [2,1][3,1][3,2]

display:
  node_size: 1500
  initial_color: 'white'
  filled_color: 'plum'
  jump_from_color: 'silver'
  jump_to_color: 'orange'
  jump_from_size: 800
  jump_to_size: 3000
  delay: 0.5 #seconds
  display_last_game: True # True or False
  plot_window_size: 20

# |------------- Agent parameters -------------|

RL_system:
  episodes: 30 # t500

critic:
  type: nn #table or NN
  dimensions: [15, 20, 30, 1] # Number of nodes in each layer
  learning_rate: 0.01 # t0.1, n0.001
  eligibility_decay: 0.1 # b0.99
  discount_factor: 0.99 # b0.99

actor:
  learning_rate: 0.1
  eligibility_decay: 0.1 # b0.9
  discount_factor: 0.9 # b0.9
  init_epsilon: 1 # b1
  epsilon_decay: 0.99 # t0.99 for 500, n0.995 for 1500