# |---------- Environment parameters ----------|

board:
  size: 5
  shape: triangle #diamond

game:
  type: Peg #Hex
  open_positions: [[3,1]]

display:
  node_size: 1500
  initial_color: 'white'
  filled_color: 'plum'
  jump_from_color: 'silver'
  jump_to_color: 'orange'
  delay: 0.5 #seconds

# |---------- Agent parameters ----------|

RL_system:
  episodes: 200

critic:
  type: NN #table or NN
  dimensions: [15, 15, 1] # Number of nodes in each layer
  learning_rate: 0.001 # If NN is used, lr for critic should be much lower than for actor
  eligibility_decay: 0.99 # Range [0,1]
  discount_factor: 0.99 # Range [0,1]

actor:
  learning_rate: 0.5
  eligibility_decay: 0.99 # Range [0,1]
  discount_factor: 0.99 # Range [0,1]
  init_epsilon: 1
  epsilon_decay_rate: 0.999
