board:
  size: 4
  shape: diamond

game:
  type: Peg
  open_cells: 1
  open_positions: [[0,0], [1,0]]

RL_system:
  episodes: 1000
  critic: table #NN

display:
  node_size: 1500
  initial_color: 'white'
  filled_color: 'plum'




