# |---------- Environment parameters ----------|

board:
  size: 4
  shape: diamond #triangle or diamond

game:
  type: Peg
  open_positions: [[3,1]]

display:
  node_size: 1500
  initial_color: 'white'
  filled_color: 'plum'
  jump_from_color: 'silver'
  jump_to_color: 'orange'
  jump_from_size: 800
  jump_to_size: 3000
  delay: 0.5 #seconds
  display_last_game: True # True or False
  plot_window_size: 20

# |------------- Agent parameters -------------|

RL_system:
  episodes: 500

critic:
  type: table #table or NN
  dimensions: [15, 1] # Number of nodes in each layer
  learning_rate: 0.1 # If NN is used, lr for critic should be much lower than for actor
  eligibility_decay: 0.99 # Range [0,1]
  discount_factor: 0.99 # Range [0,1]

actor:
  learning_rate: 0.1
  eligibility_decay: 0.9 # Range [0,1]
  discount_factor: 0.9 # Range [0,1]
  init_epsilon: 1
  epsilon_decay: 0.99