# |---------- Environment parameters ----------|

board:
  size: 4
  shape: diamond #diamond

game:
  type: Peg #Hex
  open_positions: [[2,1]]

display:
  node_size: 1500
  initial_color: 'white'
  filled_color: 'plum'
  jump_from_color: 'silver'
  jump_to_color: 'orange'
  delay: 1 #seconds

# |------------- Agent parameters -------------|

RL_system:
  episodes: 100

critic:
  type: NN #table or NN
  dimensions: [15, 20, 30, 1] # Number of nodes in each layer
  learning_rate: 0.001 # If NN is used, lr for critic should be much lower than for actor
  eligibility_decay: 0.99 # Range [0,1]
  discount_factor: 0.99 # Range [0,1]

actor:
  learning_rate: 0.1
  eligibility_decay: 0.9 # Range [0,1]
  discount_factor: 0.9 # Range [0,1]
  init_epsilon: 1
  epsilon_decay: 0.95